run_name: "sptd1_map"
lens:
  type: "candl"
  likelihood_id: "spt_candl_data.SPT3G_D1_TnE_multifreq"
parameters:
  TT_tSZ_Amp:
    initial: 2.0
    bounds: [0.0, 10.0]
  TT_kSZ_Amp:
    initial: 2.0
    bounds: [0.0, 10.0]
optimizer:
  method: "L-BFGS-B"
  tol: 1.0e-10
  options:
    maxiter: 400
